version: '3.1'
services:
  frontend:
    image: systemstat/frontend:latest
    restart: always
    build:
      context: ./
      dockerfile: ./cmd/frontend/Dockerfile
      args:
        buildno: 1
    environment:
      SYSTEMSTAT_LOG_LEVEL: TRACE
    ports:
      - 9090:9090
    depends_on:
      - db
      - database
  control:
    image: systemstat/control:latest
    restart: always
    build:
      context: ./
      dockerfile: ./cmd/control/Dockerfile
      args:
        buildno: 1
    environment:
      SYSTEMSTAT_LOG_LEVEL: TRACE
    ports:
      - 9080:9080
    depends_on:
      - db
      - database
  database:
    image: systemstat/database:latest
    restart: always
    build:
      context: ./
      dockerfile: ./cmd/database/Dockerfile
      args:
        buildno: 1
    environment:
      DATABASE_HOST: db
      DATABASE_PORT: "5432"
      DATABASE_NAME: systemstat
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SYSTEMSTAT_LOG_LEVEL: TRACE
    ports:
      - 9000:9000
    depends_on:
      - db
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: systemstat
    ports:
      - 5432:5432
    volumes:
      - ./scripts/postgres:/var/lib/postgresql/systemstat
