version: '3.1'
services:
  frontend:
    image: systemstat/frontend:latest
    restart: always
    build:
      context: ./
      dockerfile: ./cmd/frontend/Dockerfile
      args:
        buildno: 1
    environment:
      SYSTEMSTAT_LOG_LEVEL: TRACE
      SYSTEMSTAT_ADMIN_TOKEN: 419fad08-4222-47ec-a7a8-af6586d851ed
    ports:
      - 9090:9090
    healthcheck:
      test: ["CMD", "nc", "-zw1", "localhost", "9090"]
      interval: 3s
      timeout: 2s
      retries: 2
    depends_on:
      - postgres
      - database
  control:
    image: systemstat/control:latest
    restart: always
    build:
      context: ./
      dockerfile: ./cmd/control/Dockerfile
      args:
        buildno: 1
    environment:
      SYSTEMSTAT_LOG_LEVEL: TRACE
    ports:
      - 9080:9080
    healthcheck:
      test: ["CMD", "nc", "-zw1", "localhost", "9080"]
      interval: 3s
      timeout: 2s
      retries: 2
    depends_on:
      - postgres
      - database
  alert:
    image: systemstat/alert:latest
    restart: always
    build:
      context: ./
      dockerfile: ./cmd/alert/Dockerfile
      args:
        buildno: 1
    environment:
      SYSTEMSTAT_LOG_LEVEL: TRACE
    ports:
      - 9070:9070
    healthcheck:
      test: ["CMD", "nc", "-zw1", "localhost", "9070"]
      interval: 3s
      timeout: 2s
      retries: 2
    depends_on:
      - postgres
      - database
  database:
    image: systemstat/database:latest
    restart: always
    build:
      context: ./
      dockerfile: ./cmd/database/Dockerfile
      args:
        buildno: 1
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: "5432"
      DATABASE_NAME: systemstat
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      SYSTEMSTAT_LOG_LEVEL: TRACE
      GO_ENV: "development"
      GRPC_PORT: "9100"
    ports:
      # grpc
      - 9100:9100
    healthcheck:
      test: ["CMD", "/healthcheck.sh"]
      interval: 3s
      timeout: 2s
      retries: 2
    depends_on:
      - postgres
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: systemstat
    ports:
      - 15432:5432
    volumes:
      - ./scripts/postgres:/var/lib/postgresql/systemstat
